// <auto-generated />
using Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Client.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20190603103019_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Client.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<long>("CustomerId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new { Id = 1L, City = "London", CustomerId = 1L },
                        new { Id = 2L, City = "New York", CustomerId = 2L }
                    );
                });

            modelBuilder.Entity("Client.Models.ContactPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CustomerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ContactPersons");

                    b.HasData(
                        new { Id = 1L, CustomerId = 1L, Name = "John" },
                        new { Id = 2L, CustomerId = 1L, Name = "Jane" }
                    );
                });

            modelBuilder.Entity("Client.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("NameExtension");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new { Id = 1L, Name = "Company1", NameExtension = "Company1 extension" },
                        new { Id = 2L, Name = "Company2", NameExtension = "Company2 extension" }
                    );
                });

            modelBuilder.Entity("Client.Models.PhoneNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContactPersonId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new { Id = 1L, ContactPersonId = 1L, Value = "123" },
                        new { Id = 2L, ContactPersonId = 1L, Value = "456" },
                        new { Id = 3L, ContactPersonId = 2L, Value = "999" }
                    );
                });

            modelBuilder.Entity("Client.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("RoleGroupId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.ToTable("Role");

                    b.HasData(
                        new { Id = 1L, RoleGroupId = 1L, Value = "editor" },
                        new { Id = 2L, RoleGroupId = 1L, Value = "author" },
                        new { Id = 3L, RoleGroupId = 2L, Value = "admin" },
                        new { Id = 4L, RoleGroupId = 2L, Value = "editor" }
                    );
                });

            modelBuilder.Entity("Client.Models.RoleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContactPersonId");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.ToTable("RoleGroup");

                    b.HasData(
                        new { Id = 1L, ContactPersonId = 1L },
                        new { Id = 2L, ContactPersonId = 2L }
                    );
                });

            modelBuilder.Entity("Client.Models.Address", b =>
                {
                    b.HasOne("Client.Models.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("Client.Models.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Client.Models.ContactPerson", b =>
                {
                    b.HasOne("Client.Models.Customer", "Customer")
                        .WithMany("ContactPersons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Client.Models.PhoneNumber", b =>
                {
                    b.HasOne("Client.Models.ContactPerson", "ContactPerson")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Client.Models.Role", b =>
                {
                    b.HasOne("Client.Models.RoleGroup", "RoleGroup")
                        .WithMany("Roles")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Client.Models.RoleGroup", b =>
                {
                    b.HasOne("Client.Models.ContactPerson", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
